import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./layout.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VSW",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <div className="menuDiv">
          <img className="logo" src="/Logo.png" alt="logo" /><br></br>
          <a href="/">
            <h1 className="menuFont">หน้าหลัก</h1>
          </a>
          <a href="/">
            <h1 className="menuFont">บริการ</h1>
          </a>
          <a href="/">
            <h1 className="menuFont2">ช่องทางติดต่อ</h1>
          </a>
        </div>
      </body>
    </html>
  );
}
